[tools]
"npm:live-server" = "latest"
opencode = "latest"
prettier = "latest"

[tasks.format]
description = "Formats the codebase"
run = "prettier . -w"

[tasks.server]
description = "Live Website to test this"
run = "live-server"
